// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de": &dictionary{index: deIndex, data: deData},
		"en": &dictionary{index: enIndex, data: enData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"\nError: Daemon exited immediately.\n":                             155,
	"          firewall config delete interface eth0\n":                 73,
	"          firewall config delete policy \"allow ssh\" (by name)\n": 75,
	"          firewall config delete policy lan wan\n":                 74,
	"  %-10s %-6s %-8s %s\n":                                            165,
	"  %-12s %s\n":                                                      163,
	"  %s\n":                                                            157,
	"  1. Start the firewall:  %s start\n":                              147,
	"  2. Access the UI:       https://%s/\n":                           148,
	"  Allowed IPs: %v\n":                                               35,
	"  Bytes uploaded: %d\n":                                            19,
	"  Checksum: %s\n":                                                  20,
	"  Expires:     %s\n":                                               34,
	"  ID:          %s\n":                                               30,
	"  Message: %s\n":                                                   21,
	"  Name:        %s\n":                                               31,
	"  Permissions: %v\n":                                               33,
	"  Prefix:      %s\n":                                               32,
	"  Rate Limit:  %d req/min\n":                                       36,
	"  curl -H \"Authorization: Bearer %s\" http://localhost:8080/api/...\n": 37,
	"  curl -H \"X-API-Key: %s\" http://localhost:8080/api/...\n":            38,
	" with labels %v":                    77,
	"%-20s %-12s %-12s %-10d %-15s %s\n": 107,
	"%-20s %-12s %-12s %-10s %-15s %s\n": 106,
	"%s":                                 53,
	"%s\t%d\t%s\t%s\t%s\t%s\n":           214,
	"%s\t%s\t%d\n":                       216,
	"%s\t%s\n":                           215,
	"%s - %s\n\nUsage:\n  %s <command> [options]\n\nCore Commands:\n  start     Start the firewall daemon\n            Options: --foreground (-f), --dry-run (-n), --config (-c) <file>\n  stop      Stop the running daemon\n  reload    Reload configuration (hot reload)\n  status    Show daemon status\n\nManagement Commands:\n  api       Manage API keys (alias: apikey)\n            Subcommands: generate, list, revoke, help\n  config    Manage firewall configuration (HCL)\n            Subcommands: show, edit, validate, export\n  ipset     Manage IPSet blocklists\n            Subcommands: list, update, add, remove, info\n\nUtility Commands:\n  check     Validate configuration file\n            Options: --verbose (-v)\n  show      Display firewall rules\n            Options: --summary (-s), --remote (-r) <url>, --api-key (-k) <key>\n  log       View and stream system logs\n            Options: -f (follow), -n (lines), --remote <url>\n  diff      Compare two configuration files\n  import    Import configuration from other firewalls\n  console   Interactive TUI dashboard\n            Options: --remote <url>, --api-key <key>, --insecure, --debug\n  setup     First-run setup wizard\n            Options: --config-dir (-d)\n  reset     Factory reset (--confirm/-y required)\n            Options: --config-dir (-d)\n  upgrade   Seamless upgrade with socket handoff\n            Options: --binary (-b) <path>, --self, --remote (-r), --api-key (-k)\n\nExamples:\n  %s start                          # Start in background\n  %s start --foreground             # Start in foreground (debug)\n  %s start --dry-run                # Dry run (show what would happen)\n  %s stop                           # Stop the daemon\n  %s api generate --name \"monitor\" --preset readonly\n  %s check -v /etc/glacic/glacic.hcl\n  %s show --remote https://192.168.1.1:8443 --api-key xxx\n  %s log -f\n\nFor command-specific help: %s help <command>\n": 26,
	"%s API Key Management\n\nUsage:\n  %s apikey <command> [options]\n\nCommands:\n  generate    Generate a new API key\n  list        List all API keys\n  revoke      Revoke an API key\n  help        Show this help\n\nGenerate Options:\n  --name <name>           Name for the key (required)\n  --permissions <perms>   Comma-separated permissions (required)\n  --expires <duration>    Expiration (e.g., \"24h\", \"7d\", \"30d\")\n  --allowed-ips <ips>     Comma-separated allowed IPs\n  --rate-limit <rpm>      Requests per minute limit\n  --description <desc>    Description\n  --json, -j              Output in JSON format (for scripting)\n\nPermission Values:\n  Read:   config:read, uplinks:read, firewall:read, dhcp:read, dns:read,\n          learning:read, metrics:read, health:read, logs:read, read:*\n  Write:  config:write, uplinks:write, firewall:write, dhcp:write,\n          dns:write, learning:write, write:*\n  Admin:  admin:keys, admin:system, admin:backup, admin:*\n  All:    * (full access)\n\nPreset Permissions:\n  --preset readonly       Read-only access to all resources\n  --preset uplink         Uplink management (read/write uplinks, read health)\n  --preset monitoring     Metrics, health, and logs (read-only)\n  --preset admin          Full administrative access\n\nExamples:\n  # Generate a read-only key\n  %s apikey generate --name \"monitoring\" --preset readonly\n\n  # Generate an uplink control key for your script\n  %s apikey generate --name \"vpn-switcher\" --preset uplink --expires 365d\n\n  # Generate a full admin key\n  %s apikey generate --name \"admin-key\" --preset admin\n\n  # Generate a key with specific permissions\n  %s apikey generate --name \"custom\" --permissions \"uplinks:read,uplinks:write\"\n\n  # Generate a key restricted to specific IPs\n  %s apikey generate --name \"local-only\" --preset admin --allowed-ips \"127.0.0.1,192.168.1.0/24\"\n\n":                               28,
	"%s [%s] %s: %s\n":                                         134,
	"%s version %s\n":                                          12,
	"%v\n":                                                     5,
	"- %s\n":                                                   99,
	"? [y/N]: ":                                                78,
	"API Key: %s\n":                                            29,
	"Admin already exists":                                     203,
	"Age:          %s\n":                                       118,
	"Apply failed: %v\n":                                       3,
	"Apply this configuration? [y/N]: ":                        217,
	"Auth not configured":                                      200,
	"Backup created: version %d\n":                             60,
	"Build: %s\n":                                              13,
	"CIDR is required":                                         186,
	"Cache Dir:    %s\n":                                       128,
	"Cached Lists: %d\n":                                       126,
	"Cannot delete admin user":                                 208,
	"Canonicalization failed: %v\n":                            84,
	"Certificate not found":                                    191,
	"Check failed: %v\n":                                       4,
	"Clock anchor loaded: %s\n":                                90,
	"Collector not initialized":                                192,
	"Config:  %s\n":                                            161,
	"Configuration not loaded":                                 185,
	"Configuration valid!\n":                                   41,
	"Configuration validation failed: %v\n":                    57,
	"Configuration written to %s\n":                            98,
	"Connected to %s\n":                                        130,
	"Control Plane Disconnected":                               188,
	"Control plane client not connected":                       175,
	"Control plane failed: %v\n":                               2,
	"Control plane not connected":                              172,
	"Delete %s":                                                76,
	"Detected staged binary: %s\n":                             22,
	"Device ID is required":                                    179,
	"Editor failed: %v\n":                                      67,
	"Entries:      %d\n":                                       116,
	"Error applying configuration: %s\n":                       62,
	"Error deleting section: %s\n":                             80,
	"Error determining current binary path: %v\n":              11,
	"Error generating firewall rules: %v\n":                    47,
	"Error initializing firewall manager: %v\n":                48,
	"Error parsing backup: %v\n":                               95,
	"Error polling logs: %v\n":                                 133,
	"Error reading config dir: %v\n":                           150,
	"Error running console: %v\n":                              89,
	"Error writing config: %v\n":                               97,
	"Error: %v\n":                                              40,
	"Error: --api-key is required for remote connection\n":     218,
	"Error: --api-key is required for remote upgrade\n":        213,
	"Error: --binary is required for remote upgrade\n":         212,
	"Error: --input is required\n":                             219,
	"Error: API server returned status %d\n":                   102,
	"Error: Cache command is required\n":                       122,
	"Error: Failed to connect to API server: %v\n":             101,
	"Error: Failed to create request: %v\n":                    129,
	"Error: Failed to parse response: %v\n":                    104,
	"Error: Failed to read response: %v\n":                     103,
	"Error: IPSet '%s' not found\n":                            110,
	"Error: IPSet name is required\n":                          108,
	"Error: remote did not report architecture\n":              15,
	"Error: reset must run as root\n":                          149,
	"Error: setup must run as root\n":                          143,
	"Error: unsupported type '%s'\n":                           93,
	"Examples: firewall config delete dhcp\n":                  72,
	"Failed to apply configuration: %v\n":                      70,
	"Failed to clone config":                                   176,
	"Failed to connect to control plane: %v\n":                 50,
	"Failed to create temporary file: %v\n":                    65,
	"Failed to delete section: %v\n":                           79,
	"Failed to determine executable path: %v\n":                135,
	"Failed to enable debug logging: %v\n":                     88,
	"Failed to generate HCL: %v\n":                             85,
	"Failed to get configuration: %v\n":                        52,
	"Failed to get remote status: %v\n":                        14,
	"Failed to get status: %v\n":                               159,
	"Failed to initialize auth":                                205,
	"Failed to load config file: %v\n":                         82,
	"Failed to read config file: %v\n":                         55,
	"Failed to read edited file: %v\n":                         68,
	"Failed to read from stdin: %v\n":                          56,
	"Failed to read request body":                              177,
	"Failed to save migrated config: %v\n":                     86,
	"Failed to set configuration: %v\n":                        61,
	"Failed to write temporary file: %v\n":                     66,
	"Found: %d interfaces, %d filter rules, %d NAT rules\n":    96,
	"IP address is required":                                   187,
	"IPSet Cache Information:\n\n":                             125,
	"IPSet Details:\n\n":                                       111,
	"IPSets (%d total):\n\n":                                   105,
	"Interface name required":                                  183,
	"Interfaces: %d\n":                                         43,
	"Invalid DNS configuration format":                         178,
	"Invalid credentials":                                      201,
	"Invalid output format: %s\n":                              54,
	"Invalid request body":                                     173,
	"Invalid version":                                          170,
	"Is the daemon running? Start with: glacic ctl <config>\n": 158,
	"Key %s revoked.\n":                                        39,
	"Last Update:  %s\n":                                       117,
	"Log output:\n":                                            156,
	"Logs: %s\n":                                               154,
	"MAC address is required":                                  211,
	"MAC and IdentityID are required":                          180,
	"MAC is required":                                          181,
	"Make sure 'firewall ctl' is running first.\n":             51,
	"Method not allowed":                                       167,
	"Migration failed: %v\n":                                   83,
	"Migration: %s -> %s\n":                                    46,
	"Missing 'arch' field":                                     210,
	"Missing 'checksum' field":                                 209,
	"Monitor: Child crashed with exit code %d (err: %v). Restarting...\n":      139,
	"Monitor: Detected crash loop (%d fast crashes). Backing off for 30s...\n": 140,
	"Monitor: Failed to start child: %v\n":                                     136,
	"Monitor: Forwarding signal %v to child...\n":                              138,
	"Monitor: Started glacic ctl (pid=%d)\n":                                   137,
	"Name:         %s\n":                                                       112,
	"Next Update:  %s\n":                                                       119,
	"No detailed help available for '%s'\n":                                    24,
	"Options: [r]etry, [a]bort, [e]dit again: ":                                69,
	"Page not found":                                                           198,
	"Parsed backup file: %s (Type: %s)\n":                                      94,
	"Policies: %d\n":                                                           45,
	"Policy not found":                                                         194,
	"Rate limit exceeded for batch":                                            190,
	"Reload failed: %v\n":                                                      23,
	"Remote upgrade failed: %v\n":                                              17,
	"Remote upgrade initiated successfully!\n":                                 18,
	"Remote: %s (version %s, arch %s)\n":                                       16,
	"Rule not found":                                                           197,
	"Schema Version: %s\n":                                                     42,
	"Section type required (use ?type=dhcp)":                                   182,
	"Sending SIGHUP to process %d...\n":                                        142,
	"Server Certificate Fingerprint: %s\n":                                     131,
	"Setup failed: %v\n":                                                       144,
	"Show failed: %v\n":                                                        6,
	"Source URL:   %s\n":                                                       115,
	"Source:       %s\n":                                                       114,
	"Start failed: %v\n":                                                       0,
	"Started %s (PID: %d)\n":                                                   153,
	"Stop failed: %v\n":                                                        1,
	"Stopping %s (PID: %d)...\n":                                               166,
	"Successfully deleted %s":                                                  81,
	"Successfully migrated %s to schema version %s\n":                          87,
	"Task ID required":                                                         174,
	"Test run failed: %v\n":                                                    7,
	"To pin this certificate, use --fingerprint %s\n":                          132,
	"Too many login attempts. Please try again later.":                         199,
	"Too many requests in batch":                                               189,
	"Too many setup attempts. Please try again later.":                         202,
	"Total Size:   %d bytes\n":                                                 127,
	"Type:         %s\n":                                                       113,
	"Unknown cache command: %s\n":                                              124,
	"Unknown command: %s\n\n":                                                  25,
	"Unknown config command: %s\n\n":                                           49,
	"Unknown ipset command: %s\n\n":                                            100,
	"Uptime:  %s\n":                                                            160,
	"Usage: firewall config delete <section-type> [label1] [label2]...\n":      71,
	"Usage: firewall ipset cache <info|clear>\n":                               123,
	"Usage: firewall ipset refresh <name>\n":                                   121,
	"Usage: firewall ipset show <name>\n":                                      109,
	"Usage: firewall ipset update <name>\n":                                    120,
	"User not found":                                                           207,
	"Username and password required":                                           204,
	"Username required":                                                        206,
	"Validating configuration: %s\n":                                           141,
	"Validation failed: %v\n":                                                  64,
	"Version is required":                                                      168,
	"Version parameter required":                                               169,
	"Waiting for previous API instance to release lock... (%d/%d)\n":           27,
	"Warning: Failed to create backup: %s\n":                                   59,
	"Warning: Failed to create backup: %v\n":                                   58,
	"Warning: Failed to get interfaces: %v\n":                                  164,
	"Warning: Failed to get services: %v\n":                                    162,
	"Warning: Removing stale PID file %s\n":                                    152,
	"Warning: System time (%s) appears unreasonable and no anchor file exists.\n":                          92,
	"Warning: System time (%s) appears unreasonable. Last known good time was %s. Waiting for NTP sync.\n": 91,
	"Warning: failed to create admin user: %v\n":                                                           146,
	"Warning: failed to initialize auth: %v\n":                                                             145,
	"Warning: failed to remove %s: %v\n":                                                                   151,
	"You can restore from backup version %d if needed\n":                                                   63,
	"Zones: %d\n":                              44,
	"dhcp-request failed: %v\n":                10,
	"max_backups must be at least 1":           171,
	"mcast failed: %v\n":                       8,
	"mdns-publish failed: %v\n":                9,
	"name parameter required":                  184,
	"policy_name and relative_to are required": 193,
	"policy_name is required":                  195,
	"rule_name and relative_to are required":   196,
}

var deIndex = []uint32{ // 221 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001e, 0x0000003b, 0x00000061,
	0x0000007f, 0x0000009d, 0x000000ad, 0x000000ca,
	0x000000eb, 0x00000109, 0x0000012e, 0x00000153,
	0x0000018a, 0x000001a8, 0x000001bf, 0x000001ec,
	0x00000220, 0x00000254, 0x0000027b, 0x000002ac,
	0x000002ce, 0x000002ea, 0x00000305, 0x0000032d,
	0x0000034c, 0x0000037d, 0x0000039f, 0x00000b28,
	0x00000b75, 0x000012bb, 0x000012d4, 0x000012f3,
	// Entry 20 - 3F
	0x00001312, 0x00001331, 0x00001350, 0x0000136f,
	0x0000138e, 0x000013b5, 0x00001405, 0x0000144a,
	0x00001467, 0x0000147e, 0x0000149d, 0x000014bd,
	0x000014d9, 0x000014f0, 0x0000150a, 0x0000152e,
	0x0000155f, 0x00001594, 0x000015bd, 0x000015f1,
	0x00001626, 0x00001653, 0x0000165e, 0x00001685,
	0x000016b1, 0x000016dc, 0x0000170d, 0x0000173f,
	0x00001771, 0x00001799, 0x000017c6, 0x000017f4,
	// Entry 40 - 5F
	0x00001832, 0x00001855, 0x00001886, 0x000018b6,
	0x000018d5, 0x00001901, 0x00001934, 0x00001963,
	0x000019af, 0x000019df, 0x00001a19, 0x00001a53,
	0x00001a9b, 0x00001aad, 0x00001ac9, 0x00001adc,
	0x00001b06, 0x00001b2e, 0x00001b4e, 0x00001b7a,
	0x00001b9c, 0x00001bc5, 0x00001bed, 0x00001c1d,
	0x00001c5b, 0x00001c8b, 0x00001cb2, 0x00001cd7,
	0x00001d4a, 0x00001da1, 0x00001dcb, 0x00001dfd,
	// Entry 60 - 7F
	0x00001e23, 0x00001e6a, 0x00001e90, 0x00001eb9,
	0x00001ecb, 0x00001ef3, 0x00001f2b, 0x00001f5d,
	0x00001f8d, 0x00001fbe, 0x00001fdf, 0x0000201c,
	0x00002059, 0x00002081, 0x000020ad, 0x000020d6,
	0x000020f0, 0x0000210e, 0x0000212c, 0x0000214a,
	0x00002168, 0x00002186, 0x000021a4, 0x000021c2,
	0x000021e0, 0x0000220e, 0x0000223d, 0x00002268,
	0x0000229b, 0x000022c2, 0x000022e6, 0x00002304,
	// Entry 80 - 9F
	0x00002328, 0x00002346, 0x00002377, 0x00002394,
	0x000023c4, 0x000023ff, 0x00002423, 0x00002448,
	0x0000247d, 0x000024ad, 0x000024df, 0x00002516,
	0x00002568, 0x000025bc, 0x000025e6, 0x00002613,
	0x0000263b, 0x00002659, 0x0000268d, 0x000026c3,
	0x000026f3, 0x00002726, 0x0000274e, 0x00002778,
	0x000027a9, 0x000027da, 0x000027ff, 0x00002815,
	0x00002842, 0x00002858, 0x0000286a, 0x000028ab,
	// Entry A0 - BF
	0x000028d1, 0x000028ea, 0x00002903, 0x00002934,
	0x0000294f, 0x00002982, 0x000029ad, 0x000029d6,
	0x000029ee, 0x00002a07, 0x00002a27, 0x00002a3c,
	0x00002a60, 0x00002a81, 0x00002a9b, 0x00002ab1,
	0x00002ad9, 0x00002af5, 0x00002b16, 0x00002b3c,
	0x00002b57, 0x00002b7c, 0x00002b91, 0x00002bbd,
	0x00002bda, 0x00002bf7, 0x00002c15, 0x00002c2b,
	0x00002c47, 0x00002c67, 0x00002c87, 0x00002caa,
	// Entry C0 - DF
	0x00002cc5, 0x00002ce4, 0x00002d12, 0x00002d28,
	0x00002d45, 0x00002d71, 0x00002d85, 0x00002d99,
	0x00002dcf, 0x00002de8, 0x00002e01, 0x00002e37,
	0x00002e51, 0x00002e75, 0x00002e94, 0x00002eab,
	0x00002ebf, 0x00002edd, 0x00002efb, 0x00002f15,
	0x00002f32, 0x00002f32, 0x00002f32, 0x00002f32,
	0x00002f32, 0x00002f32, 0x00002f32, 0x00002f32,
	0x00002f32,
} // Size: 908 bytes

const deData string = "" + // Size: 12082 bytes
	"\x04\x00\x01\x0a\x19\x02[DE] Start failed: %[1]v\x04\x00\x01\x0a\x18\x02" +
	"[DE] Stop failed: %[1]v\x04\x00\x01\x0a!\x02[DE] Control plane failed: %" +
	"[1]v\x04\x00\x01\x0a\x19\x02[DE] Apply failed: %[1]v\x04\x00\x01\x0a\x19" +
	"\x02[DE] Check failed: %[1]v\x04\x00\x01\x0a\x0b\x02[DE] %[1]v\x04\x00" +
	"\x01\x0a\x18\x02[DE] Show failed: %[1]v\x04\x00\x01\x0a\x1c\x02[DE] Test" +
	" run failed: %[1]v\x04\x00\x01\x0a\x19\x02[DE] mcast failed: %[1]v\x04" +
	"\x00\x01\x0a \x02[DE] mdns-publish failed: %[1]v\x04\x00\x01\x0a \x02[DE" +
	"] dhcp-request failed: %[1]v\x04\x00\x01\x0a2\x02[DE] Error determining " +
	"current binary path: %[1]v\x04\x00\x01\x0a\x19\x02[DE] %[1]s version %[2" +
	"]s\x04\x00\x01\x0a\x12\x02[DE] Build: %[1]s\x04\x00\x01\x0a(\x02[DE] Fai" +
	"led to get remote status: %[1]v\x04\x00\x01\x0a/\x02[DE] Error: remote d" +
	"id not report architecture\x04\x00\x01\x0a/\x02[DE] Remote: %[1]s (versi" +
	"on %[2]s, arch %[3]s)\x04\x00\x01\x0a\x22\x02[DE] Remote upgrade failed:" +
	" %[1]v\x04\x00\x01\x0a,\x02[DE] Remote upgrade initiated successfully!" +
	"\x04\x02  \x01\x0a\x1b\x02[DE] Bytes uploaded: %[1]d\x04\x02  \x01\x0a" +
	"\x15\x02[DE] Checksum: %[1]s\x04\x02  \x01\x0a\x14\x02[DE] Message: %[1]" +
	"s\x04\x00\x01\x0a#\x02[DE] Detected staged binary: %[1]s\x04\x00\x01\x0a" +
	"\x1a\x02[DE] Reload failed: %[1]v\x04\x00\x01\x0a,\x02[DE] No detailed h" +
	"elp available for '%[1]s'\x04\x00\x02\x0a\x0a\x1c\x02[DE] Unknown comman" +
	"d: %[1]s\x04\x00\x01\x0a\x83\x0f\x02[DE] %[1]s - %[2]s\x0a\x0aUsage:\x0a" +
	"  %[3]s <command> [options]\x0a\x0aCore Commands:\x0a  start     Start t" +
	"he firewall daemon\x0a            Options: --foreground (-f), --dry-run " +
	"(-n), --config (-c) <file>\x0a  stop      Stop the running daemon\x0a  r" +
	"eload    Reload configuration (hot reload)\x0a  status    Show daemon st" +
	"atus\x0a\x0aManagement Commands:\x0a  api       Manage API keys (alias: " +
	"apikey)\x0a            Subcommands: generate, list, revoke, help\x0a  co" +
	"nfig    Manage firewall configuration (HCL)\x0a            Subcommands: " +
	"show, edit, validate, export\x0a  ipset     Manage IPSet blocklists\x0a " +
	"           Subcommands: list, update, add, remove, info\x0a\x0aUtility C" +
	"ommands:\x0a  check     Validate configuration file\x0a            Optio" +
	"ns: --verbose (-v)\x0a  show      Display firewall rules\x0a            " +
	"Options: --summary (-s), --remote (-r) <url>, --api-key (-k) <key>\x0a  " +
	"log       View and stream system logs\x0a            Options: -f (follow" +
	"), -n (lines), --remote <url>\x0a  diff      Compare two configuration f" +
	"iles\x0a  import    Import configuration from other firewalls\x0a  conso" +
	"le   Interactive TUI dashboard\x0a            Options: --remote <url>, -" +
	"-api-key <key>, --insecure, --debug\x0a  setup     First-run setup wizar" +
	"d\x0a            Options: --config-dir (-d)\x0a  reset     Factory reset" +
	" (--confirm/-y required)\x0a            Options: --config-dir (-d)\x0a  " +
	"upgrade   Seamless upgrade with socket handoff\x0a            Options: -" +
	"-binary (-b) <path>, --self, --remote (-r), --api-key (-k)\x0a\x0aExampl" +
	"es:\x0a  %[4]s start                          # Start in background\x0a " +
	" %[5]s start --foreground             # Start in foreground (debug)\x0a " +
	" %[6]s start --dry-run                # Dry run (show what would happen)" +
	"\x0a  %[7]s stop                           # Stop the daemon\x0a  %[8]s " +
	"api generate --name \x22monitor\x22 --preset readonly\x0a  %[9]s check -" +
	"v /etc/glacic/glacic.hcl\x0a  %[10]s show --remote https://192.168.1.1:8" +
	"443 --api-key xxx\x0a  %[11]s log -f\x0a\x0aFor command-specific help: %" +
	"[12]s help <command>\x04\x00\x01\x0aH\x02[DE] Waiting for previous API i" +
	"nstance to release lock... (%[1]d/%[2]d)\x04\x00\x02\x0a\x0a\xbf\x0e\x02" +
	"[DE] %[1]s API Key Management\x0a\x0aUsage:\x0a  %[2]s apikey <command> " +
	"[options]\x0a\x0aCommands:\x0a  generate    Generate a new API key\x0a  " +
	"list        List all API keys\x0a  revoke      Revoke an API key\x0a  he" +
	"lp        Show this help\x0a\x0aGenerate Options:\x0a  --name <name>    " +
	"       Name for the key (required)\x0a  --permissions <perms>   Comma-se" +
	"parated permissions (required)\x0a  --expires <duration>    Expiration (" +
	"e.g., \x2224h\x22, \x227d\x22, \x2230d\x22)\x0a  --allowed-ips <ips>    " +
	" Comma-separated allowed IPs\x0a  --rate-limit <rpm>      Requests per m" +
	"inute limit\x0a  --description <desc>    Description\x0a  --json, -j    " +
	"          Output in JSON format (for scripting)\x0a\x0aPermission Values" +
	":\x0a  Read:   config:read, uplinks:read, firewall:read, dhcp:read, dns:" +
	"read,\x0a          learning:read, metrics:read, health:read, logs:read, " +
	"read:*\x0a  Write:  config:write, uplinks:write, firewall:write, dhcp:wr" +
	"ite,\x0a          dns:write, learning:write, write:*\x0a  Admin:  admin:" +
	"keys, admin:system, admin:backup, admin:*\x0a  All:    * (full access)" +
	"\x0a\x0aPreset Permissions:\x0a  --preset readonly       Read-only acces" +
	"s to all resources\x0a  --preset uplink         Uplink management (read/" +
	"write uplinks, read health)\x0a  --preset monitoring     Metrics, health" +
	", and logs (read-only)\x0a  --preset admin          Full administrative " +
	"access\x0a\x0aExamples:\x0a  # Generate a read-only key\x0a  %[3]s apike" +
	"y generate --name \x22monitoring\x22 --preset readonly\x0a\x0a  # Genera" +
	"te an uplink control key for your script\x0a  %[4]s apikey generate --na" +
	"me \x22vpn-switcher\x22 --preset uplink --expires 365d\x0a\x0a  # Genera" +
	"te a full admin key\x0a  %[5]s apikey generate --name \x22admin-key\x22 " +
	"--preset admin\x0a\x0a  # Generate a key with specific permissions\x0a  " +
	"%[6]s apikey generate --name \x22custom\x22 --permissions \x22uplinks:re" +
	"ad,uplinks:write\x22\x0a\x0a  # Generate a key restricted to specific IP" +
	"s\x0a  %[7]s apikey generate --name \x22local-only\x22 --preset admin --" +
	"allowed-ips \x22127.0.0.1,192.168.1.0/24\x22\x04\x00\x01\x0a\x14\x02[DE]" +
	" API Key: %[1]s\x04\x02  \x01\x0a\x18\x02[DE] ID:          %[1]s\x04\x02" +
	"  \x01\x0a\x18\x02[DE] Name:        %[1]s\x04\x02  \x01\x0a\x18\x02[DE] " +
	"Prefix:      %[1]s\x04\x02  \x01\x0a\x18\x02[DE] Permissions: %[1]v\x04" +
	"\x02  \x01\x0a\x18\x02[DE] Expires:     %[1]s\x04\x02  \x01\x0a\x18\x02[" +
	"DE] Allowed IPs: %[1]v\x04\x02  \x01\x0a \x02[DE] Rate Limit:  %[1]d req" +
	"/min\x04\x02  \x01\x0aI\x02[DE] curl -H \x22Authorization: Bearer %[1]s" +
	"\x22 http://localhost:8080/api/...\x04\x02  \x01\x0a>\x02[DE] curl -H " +
	"\x22X-API-Key: %[1]s\x22 http://localhost:8080/api/...\x04\x00\x01\x0a" +
	"\x18\x02[DE] Key %[1]s revoked.\x04\x00\x01\x0a\x12\x02[DE] Error: %[1]v" +
	"\x04\x00\x01\x0a\x1a\x02[DE] Configuration valid!\x04\x00\x01\x0a\x1b" +
	"\x02[DE] Schema Version: %[1]s\x04\x00\x01\x0a\x17\x02[DE] Interfaces: %" +
	"[1]d\x04\x00\x01\x0a\x12\x02[DE] Zones: %[1]d\x04\x00\x01\x0a\x15\x02[DE" +
	"] Policies: %[1]d\x04\x00\x01\x0a\x1f\x02[DE] Migration: %[1]s -> %[2]s" +
	"\x04\x00\x01\x0a,\x02[DE] Error generating firewall rules: %[1]v\x04\x00" +
	"\x01\x0a0\x02[DE] Error initializing firewall manager: %[1]v\x04\x00\x02" +
	"\x0a\x0a#\x02[DE] Unknown config command: %[1]s\x04\x00\x01\x0a/\x02[DE]" +
	" Failed to connect to control plane: %[1]v\x04\x00\x01\x0a0\x02[DE] Make" +
	" sure 'firewall ctl' is running first.\x04\x00\x01\x0a(\x02[DE] Failed t" +
	"o get configuration: %[1]v\x02[DE] %[1]s\x04\x00\x01\x0a\x22\x02[DE] Inv" +
	"alid output format: %[1]s\x04\x00\x01\x0a'\x02[DE] Failed to read config" +
	" file: %[1]v\x04\x00\x01\x0a&\x02[DE] Failed to read from stdin: %[1]v" +
	"\x04\x00\x01\x0a,\x02[DE] Configuration validation failed: %[1]v\x04\x00" +
	"\x01\x0a-\x02[DE] Warning: Failed to create backup: %[1]v\x04\x00\x01" +
	"\x0a-\x02[DE] Warning: Failed to create backup: %[1]s\x04\x00\x01\x0a#" +
	"\x02[DE] Backup created: version %[1]d\x04\x00\x01\x0a(\x02[DE] Failed t" +
	"o set configuration: %[1]v\x04\x00\x01\x0a)\x02[DE] Error applying confi" +
	"guration: %[1]s\x04\x00\x01\x0a9\x02[DE] You can restore from backup ver" +
	"sion %[1]d if needed\x04\x00\x01\x0a\x1e\x02[DE] Validation failed: %[1]" +
	"v\x04\x00\x01\x0a,\x02[DE] Failed to create temporary file: %[1]v\x04" +
	"\x00\x01\x0a+\x02[DE] Failed to write temporary file: %[1]v\x04\x00\x01" +
	"\x0a\x1a\x02[DE] Editor failed: %[1]v\x04\x00\x01\x0a'\x02[DE] Failed to" +
	" read edited file: %[1]v\x04\x00\x01 .\x02[DE] Options: [r]etry, [a]bort" +
	", [e]dit again:\x04\x00\x01\x0a*\x02[DE] Failed to apply configuration: " +
	"%[1]v\x04\x00\x01\x0aG\x02[DE] Usage: firewall config delete <section-ty" +
	"pe> [label1] [label2]...\x04\x00\x01\x0a+\x02[DE] Examples: firewall con" +
	"fig delete dhcp\x04\x0a          \x01\x0a+\x02[DE] firewall config delet" +
	"e interface eth0\x04\x0a          \x01\x0a+\x02[DE] firewall config dele" +
	"te policy lan wan\x04\x0a          \x01\x0a9\x02[DE] firewall config del" +
	"ete policy \x22allow ssh\x22 (by name)\x02[DE] Delete %[1]s\x04\x01 \x00" +
	"\x17\x02[DE] with labels %[1]v\x04\x00\x01 \x0e\x02[DE] ? [y/N]:\x04\x00" +
	"\x01\x0a%\x02[DE] Failed to delete section: %[1]v\x04\x00\x01\x0a#\x02[D" +
	"E] Error deleting section: %[1]s\x02[DE] Successfully deleted %[1]s\x04" +
	"\x00\x01\x0a'\x02[DE] Failed to load config file: %[1]v\x04\x00\x01\x0a" +
	"\x1d\x02[DE] Migration failed: %[1]v\x04\x00\x01\x0a$\x02[DE] Canonicali" +
	"zation failed: %[1]v\x04\x00\x01\x0a#\x02[DE] Failed to generate HCL: %[" +
	"1]v\x04\x00\x01\x0a+\x02[DE] Failed to save migrated config: %[1]v\x04" +
	"\x00\x01\x0a9\x02[DE] Successfully migrated %[1]s to schema version %[2]" +
	"s\x04\x00\x01\x0a+\x02[DE] Failed to enable debug logging: %[1]v\x04\x00" +
	"\x01\x0a\x22\x02[DE] Error running console: %[1]v\x04\x00\x01\x0a \x02[D" +
	"E] Clock anchor loaded: %[1]s\x04\x00\x01\x0an\x02[DE] Warning: System t" +
	"ime (%[1]s) appears unreasonable. Last known good time was %[2]s. Waitin" +
	"g for NTP sync.\x04\x00\x01\x0aR\x02[DE] Warning: System time (%[1]s) ap" +
	"pears unreasonable and no anchor file exists.\x04\x00\x01\x0a%\x02[DE] E" +
	"rror: unsupported type '%[1]s'\x04\x00\x01\x0a-\x02[DE] Parsed backup fi" +
	"le: %[1]s (Type: %[2]s)\x04\x00\x01\x0a!\x02[DE] Error parsing backup: %" +
	"[1]v\x04\x00\x01\x0aB\x02[DE] Found: %[1]d interfaces, %[2]d filter rule" +
	"s, %[3]d NAT rules\x04\x00\x01\x0a!\x02[DE] Error writing config: %[1]v" +
	"\x04\x00\x01\x0a$\x02[DE] Configuration written to %[1]s\x04\x00\x01\x0a" +
	"\x0d\x02[DE] - %[1]s\x04\x00\x02\x0a\x0a\x22\x02[DE] Unknown ipset comma" +
	"nd: %[1]s\x04\x00\x01\x0a3\x02[DE] Error: Failed to connect to API serve" +
	"r: %[1]v\x04\x00\x01\x0a-\x02[DE] Error: API server returned status %[1]" +
	"d\x04\x00\x01\x0a+\x02[DE] Error: Failed to read response: %[1]v\x04\x00" +
	"\x01\x0a,\x02[DE] Error: Failed to parse response: %[1]v\x04\x00\x02\x0a" +
	"\x0a\x1b\x02[DE] IPSets (%[1]d total):\x04\x00\x01\x0a8\x02[DE] %-20[1]s" +
	" %-12[2]s %-12[3]s %-10[4]s %-15[5]s %[6]s\x04\x00\x01\x0a8\x02[DE] %-20" +
	"[1]s %-12[2]s %-12[3]s %-10[4]d %-15[5]s %[6]s\x04\x00\x01\x0a#\x02[DE] " +
	"Error: IPSet name is required\x04\x00\x01\x0a'\x02[DE] Usage: firewall i" +
	"pset show <name>\x04\x00\x01\x0a$\x02[DE] Error: IPSet '%[1]s' not found" +
	"\x04\x00\x02\x0a\x0a\x14\x02[DE] IPSet Details:\x04\x00\x01\x0a\x19\x02[" +
	"DE] Name:         %[1]s\x04\x00\x01\x0a\x19\x02[DE] Type:         %[1]s" +
	"\x04\x00\x01\x0a\x19\x02[DE] Source:       %[1]s\x04\x00\x01\x0a\x19\x02" +
	"[DE] Source URL:   %[1]s\x04\x00\x01\x0a\x19\x02[DE] Entries:      %[1]d" +
	"\x04\x00\x01\x0a\x19\x02[DE] Last Update:  %[1]s\x04\x00\x01\x0a\x19\x02" +
	"[DE] Age:          %[1]s\x04\x00\x01\x0a\x19\x02[DE] Next Update:  %[1]s" +
	"\x04\x00\x01\x0a)\x02[DE] Usage: firewall ipset update <name>\x04\x00" +
	"\x01\x0a*\x02[DE] Usage: firewall ipset refresh <name>\x04\x00\x01\x0a&" +
	"\x02[DE] Error: Cache command is required\x04\x00\x01\x0a.\x02[DE] Usage" +
	": firewall ipset cache <info|clear>\x04\x00\x01\x0a\x22\x02[DE] Unknown " +
	"cache command: %[1]s\x04\x00\x02\x0a\x0a\x1e\x02[DE] IPSet Cache Informa" +
	"tion:\x04\x00\x01\x0a\x19\x02[DE] Cached Lists: %[1]d\x04\x00\x01\x0a" +
	"\x1f\x02[DE] Total Size:   %[1]d bytes\x04\x00\x01\x0a\x19\x02[DE] Cache" +
	" Dir:    %[1]s\x04\x00\x01\x0a,\x02[DE] Error: Failed to create request:" +
	" %[1]v\x04\x00\x01\x0a\x18\x02[DE] Connected to %[1]s\x04\x00\x01\x0a+" +
	"\x02[DE] Server Certificate Fingerprint: %[1]s\x04\x00\x01\x0a6\x02[DE] " +
	"To pin this certificate, use --fingerprint %[1]s\x04\x00\x01\x0a\x1f\x02" +
	"[DE] Error polling logs: %[1]v\x04\x00\x01\x0a \x02[DE] %[1]s [%[2]s] %[" +
	"3]s: %[4]s\x04\x00\x01\x0a0\x02[DE] Failed to determine executable path:" +
	" %[1]v\x04\x00\x01\x0a+\x02[DE] Monitor: Failed to start child: %[1]v" +
	"\x04\x00\x01\x0a-\x02[DE] Monitor: Started glacic ctl (pid=%[1]d)\x04" +
	"\x00\x01\x0a2\x02[DE] Monitor: Forwarding signal %[1]v to child...\x04" +
	"\x00\x01\x0aM\x02[DE] Monitor: Child crashed with exit code %[1]d (err: " +
	"%[2]v). Restarting...\x04\x00\x01\x0aO\x02[DE] Monitor: Detected crash l" +
	"oop (%[1]d fast crashes). Backing off for 30s...\x04\x00\x01\x0a%\x02[DE" +
	"] Validating configuration: %[1]s\x04\x00\x01\x0a(\x02[DE] Sending SIGHU" +
	"P to process %[1]d...\x04\x00\x01\x0a#\x02[DE] Error: setup must run as " +
	"root\x04\x00\x01\x0a\x19\x02[DE] Setup failed: %[1]v\x04\x00\x01\x0a/" +
	"\x02[DE] Warning: failed to initialize auth: %[1]v\x04\x00\x01\x0a1\x02[" +
	"DE] Warning: failed to create admin user: %[1]v\x04\x02  \x01\x0a)\x02[D" +
	"E] 1. Start the firewall:  %[1]s start\x04\x02  \x01\x0a,\x02[DE] 2. Acc" +
	"ess the UI:       https://%[1]s/\x04\x00\x01\x0a#\x02[DE] Error: reset m" +
	"ust run as root\x04\x00\x01\x0a%\x02[DE] Error reading config dir: %[1]v" +
	"\x04\x00\x01\x0a,\x02[DE] Warning: failed to remove %[1]s: %[2]v\x04\x00" +
	"\x01\x0a,\x02[DE] Warning: Removing stale PID file %[1]s\x04\x00\x01\x0a" +
	" \x02[DE] Started %[1]s (PID: %[2]d)\x04\x00\x01\x0a\x11\x02[DE] Logs: %" +
	"[1]s\x04\x01\x0a\x01\x0a'\x02[DE] Error: Daemon exited immediately.\x04" +
	"\x00\x01\x0a\x11\x02[DE] Log output:\x04\x02  \x01\x0a\x0b\x02[DE] %[1]s" +
	"\x04\x00\x01\x0a<\x02[DE] Is the daemon running? Start with: glacic ctl " +
	"<config>\x04\x00\x01\x0a!\x02[DE] Failed to get status: %[1]v\x04\x00" +
	"\x01\x0a\x14\x02[DE] Uptime:  %[1]s\x04\x00\x01\x0a\x14\x02[DE] Config: " +
	" %[1]s\x04\x00\x01\x0a,\x02[DE] Warning: Failed to get services: %[1]v" +
	"\x04\x02  \x01\x0a\x14\x02[DE] %-12[1]s %[2]s\x04\x00\x01\x0a.\x02[DE] W" +
	"arning: Failed to get interfaces: %[1]v\x04\x02  \x01\x0a$\x02[DE] %-10[" +
	"1]s %-6[2]s %-8[3]s %[4]s\x04\x00\x01\x0a$\x02[DE] Stopping %[1]s (PID: " +
	"%[2]d)...\x02[DE] Method not allowed\x02[DE] Version is required\x02[DE]" +
	" Version parameter required\x02[DE] Invalid version\x02[DE] max_backups " +
	"must be at least 1\x02[DE] Control plane not connected\x02[DE] Invalid r" +
	"equest body\x02[DE] Task ID required\x02[DE] Control plane client not co" +
	"nnected\x02[DE] Failed to clone config\x02[DE] Failed to read request bo" +
	"dy\x02[DE] Invalid DNS configuration format\x02[DE] Device ID is require" +
	"d\x02[DE] MAC and IdentityID are required\x02[DE] MAC is required\x02[DE" +
	"] Section type required (use ?type=dhcp)\x02[DE] Interface name required" +
	"\x02[DE] name parameter required\x02[DE] Configuration not loaded\x02[DE" +
	"] CIDR is required\x02[DE] IP address is required\x02[DE] Control Plane " +
	"Disconnected\x02[DE] Too many requests in batch\x02[DE] Rate limit excee" +
	"ded for batch\x02[DE] Certificate not found\x02[DE] Collector not initia" +
	"lized\x02[DE] policy_name and relative_to are required\x02[DE] Policy no" +
	"t found\x02[DE] policy_name is required\x02[DE] rule_name and relative_t" +
	"o are required\x02[DE] Rule not found\x02[DE] Page not found\x02[DE] Too" +
	" many login attempts. Please try again later.\x02[DE] Auth not configure" +
	"d\x02[DE] Invalid credentials\x02[DE] Too many setup attempts. Please tr" +
	"y again later.\x02[DE] Admin already exists\x02[DE] Username and passwor" +
	"d required\x02[DE] Failed to initialize auth\x02[DE] Username required" +
	"\x02[DE] User not found\x02[DE] Cannot delete admin user\x02[DE] Missing" +
	" 'checksum' field\x02[DE] Missing 'arch' field\x02[DE] MAC address is re" +
	"quired"

var enIndex = []uint32{ // 221 elements
	// Entry 0 - 1F
	0x00000000, 0x00000019, 0x00000031, 0x00000052,
	0x0000006b, 0x00000084, 0x0000008f, 0x000000a7,
	0x000000c3, 0x000000dc, 0x000000fc, 0x0000011c,
	0x0000014e, 0x00000167, 0x00000179, 0x000001a1,
	0x000001d0, 0x000001ff, 0x00000221, 0x0000024d,
	0x0000026a, 0x00000281, 0x00000297, 0x000002ba,
	0x000002d4, 0x00000300, 0x0000031d, 0x00000aa1,
	0x00000ae9, 0x0000122a, 0x0000123e, 0x00001258,
	// Entry 20 - 3F
	0x00001272, 0x0000128c, 0x000012a6, 0x000012c0,
	0x000012da, 0x000012fc, 0x00001347, 0x00001387,
	0x0000139f, 0x000013b1, 0x000013cb, 0x000013e6,
	0x000013fd, 0x0000140f, 0x00001424, 0x00001443,
	0x0000146f, 0x0000149f, 0x000014c3, 0x000014f2,
	0x00001522, 0x0000154a, 0x00001550, 0x00001572,
	0x00001599, 0x000015bf, 0x000015eb, 0x00001618,
	0x00001645, 0x00001668, 0x00001690, 0x000016b9,
	// Entry 40 - 5F
	0x000016f2, 0x00001710, 0x0000173c, 0x00001767,
	0x00001781, 0x000017a8, 0x000017d6, 0x00001800,
	0x00001847, 0x00001872, 0x000018a7, 0x000018dc,
	0x0000191f, 0x0000192c, 0x00001943, 0x00001951,
	0x00001976, 0x00001999, 0x000019b4, 0x000019db,
	0x000019f8, 0x00001a1c, 0x00001a3f, 0x00001a6a,
	0x00001aa3, 0x00001ace, 0x00001af0, 0x00001b10,
	0x00001b7e, 0x00001bd0, 0x00001bf5, 0x00001c22,
	// Entry 60 - 7F
	0x00001c43, 0x00001c85, 0x00001ca6, 0x00001cca,
	0x00001cd7, 0x00001cfa, 0x00001d2d, 0x00001d5a,
	0x00001d85, 0x00001db1, 0x00001dcd, 0x00001e05,
	0x00001e3d, 0x00001e60, 0x00001e87, 0x00001eab,
	0x00001ec0, 0x00001ed9, 0x00001ef2, 0x00001f0b,
	0x00001f24, 0x00001f3d, 0x00001f56, 0x00001f6f,
	0x00001f88, 0x00001fb1, 0x00001fdb, 0x00002001,
	0x0000202f, 0x00002051, 0x00002070, 0x00002089,
	// Entry 80 - 9F
	0x000020a8, 0x000020c1, 0x000020ed, 0x00002105,
	0x00002130, 0x00002166, 0x00002185, 0x000021a5,
	0x000021d5, 0x00002200, 0x0000222d, 0x0000225f,
	0x000022ac, 0x000022fb, 0x00002320, 0x00002348,
	0x0000236b, 0x00002384, 0x000023b3, 0x000023e4,
	0x0000240f, 0x0000243d, 0x00002460, 0x00002485,
	0x000024b1, 0x000024dd, 0x000024fd, 0x0000250e,
	0x00002536, 0x00002547, 0x00002554, 0x00002590,
	// Entry A0 - BF
	0x000025b1, 0x000025c5, 0x000025d9, 0x00002605,
	0x0000261b, 0x00002649, 0x0000266f, 0x00002693,
	0x000026a6, 0x000026ba, 0x000026d5, 0x000026e5,
	0x00002704, 0x00002720, 0x00002735, 0x00002746,
	0x00002769, 0x00002780, 0x0000279c, 0x000027bd,
	0x000027d3, 0x000027f3, 0x00002803, 0x0000282a,
	0x00002842, 0x0000285a, 0x00002873, 0x00002884,
	0x0000289b, 0x000028b6, 0x000028d1, 0x000028ef,
	// Entry C0 - DF
	0x00002905, 0x0000291f, 0x00002948, 0x00002959,
	0x00002971, 0x00002998, 0x000029a7, 0x000029b6,
	0x000029e7, 0x000029fb, 0x00002a0f, 0x00002a40,
	0x00002a55, 0x00002a74, 0x00002a8e, 0x00002aa0,
	0x00002aaf, 0x00002ac8, 0x00002ae1, 0x00002af6,
	0x00002b0e, 0x00002b42, 0x00002b77, 0x00002ba0,
	0x00002bb1, 0x00002bc8, 0x00002bee, 0x00002c26,
	0x00002c46,
} // Size: 908 bytes

const enData string = "" + // Size: 11334 bytes
	"\x04\x00\x01\x0a\x14\x02Start failed: %[1]v\x04\x00\x01\x0a\x13\x02Stop " +
	"failed: %[1]v\x04\x00\x01\x0a\x1c\x02Control plane failed: %[1]v\x04\x00" +
	"\x01\x0a\x14\x02Apply failed: %[1]v\x04\x00\x01\x0a\x14\x02Check failed:" +
	" %[1]v\x04\x00\x01\x0a\x06\x02%[1]v\x04\x00\x01\x0a\x13\x02Show failed: " +
	"%[1]v\x04\x00\x01\x0a\x17\x02Test run failed: %[1]v\x04\x00\x01\x0a\x14" +
	"\x02mcast failed: %[1]v\x04\x00\x01\x0a\x1b\x02mdns-publish failed: %[1]" +
	"v\x04\x00\x01\x0a\x1b\x02dhcp-request failed: %[1]v\x04\x00\x01\x0a-\x02" +
	"Error determining current binary path: %[1]v\x04\x00\x01\x0a\x14\x02%[1]" +
	"s version %[2]s\x04\x00\x01\x0a\x0d\x02Build: %[1]s\x04\x00\x01\x0a#\x02" +
	"Failed to get remote status: %[1]v\x04\x00\x01\x0a*\x02Error: remote did" +
	" not report architecture\x04\x00\x01\x0a*\x02Remote: %[1]s (version %[2]" +
	"s, arch %[3]s)\x04\x00\x01\x0a\x1d\x02Remote upgrade failed: %[1]v\x04" +
	"\x00\x01\x0a'\x02Remote upgrade initiated successfully!\x04\x02  \x01" +
	"\x0a\x16\x02Bytes uploaded: %[1]d\x04\x02  \x01\x0a\x10\x02Checksum: %[1" +
	"]s\x04\x02  \x01\x0a\x0f\x02Message: %[1]s\x04\x00\x01\x0a\x1e\x02Detect" +
	"ed staged binary: %[1]s\x04\x00\x01\x0a\x15\x02Reload failed: %[1]v\x04" +
	"\x00\x01\x0a'\x02No detailed help available for '%[1]s'\x04\x00\x02\x0a" +
	"\x0a\x17\x02Unknown command: %[1]s\x04\x00\x01\x0a\xfe\x0e\x02%[1]s - %[" +
	"2]s\x0a\x0aUsage:\x0a  %[3]s <command> [options]\x0a\x0aCore Commands:" +
	"\x0a  start     Start the firewall daemon\x0a            Options: --fore" +
	"ground (-f), --dry-run (-n), --config (-c) <file>\x0a  stop      Stop th" +
	"e running daemon\x0a  reload    Reload configuration (hot reload)\x0a  s" +
	"tatus    Show daemon status\x0a\x0aManagement Commands:\x0a  api       M" +
	"anage API keys (alias: apikey)\x0a            Subcommands: generate, lis" +
	"t, revoke, help\x0a  config    Manage firewall configuration (HCL)\x0a  " +
	"          Subcommands: show, edit, validate, export\x0a  ipset     Manag" +
	"e IPSet blocklists\x0a            Subcommands: list, update, add, remove" +
	", info\x0a\x0aUtility Commands:\x0a  check     Validate configuration fi" +
	"le\x0a            Options: --verbose (-v)\x0a  show      Display firewal" +
	"l rules\x0a            Options: --summary (-s), --remote (-r) <url>, --a" +
	"pi-key (-k) <key>\x0a  log       View and stream system logs\x0a        " +
	"    Options: -f (follow), -n (lines), --remote <url>\x0a  diff      Comp" +
	"are two configuration files\x0a  import    Import configuration from oth" +
	"er firewalls\x0a  console   Interactive TUI dashboard\x0a            Opt" +
	"ions: --remote <url>, --api-key <key>, --insecure, --debug\x0a  setup   " +
	"  First-run setup wizard\x0a            Options: --config-dir (-d)\x0a  " +
	"reset     Factory reset (--confirm/-y required)\x0a            Options: " +
	"--config-dir (-d)\x0a  upgrade   Seamless upgrade with socket handoff" +
	"\x0a            Options: --binary (-b) <path>, --self, --remote (-r), --" +
	"api-key (-k)\x0a\x0aExamples:\x0a  %[4]s start                          " +
	"# Start in background\x0a  %[5]s start --foreground             # Start " +
	"in foreground (debug)\x0a  %[6]s start --dry-run                # Dry ru" +
	"n (show what would happen)\x0a  %[7]s stop                           # S" +
	"top the daemon\x0a  %[8]s api generate --name \x22monitor\x22 --preset r" +
	"eadonly\x0a  %[9]s check -v /etc/glacic/glacic.hcl\x0a  %[10]s show --re" +
	"mote https://192.168.1.1:8443 --api-key xxx\x0a  %[11]s log -f\x0a\x0aFo" +
	"r command-specific help: %[12]s help <command>\x04\x00\x01\x0aC\x02Waiti" +
	"ng for previous API instance to release lock... (%[1]d/%[2]d)\x04\x00" +
	"\x02\x0a\x0a\xba\x0e\x02%[1]s API Key Management\x0a\x0aUsage:\x0a  %[2]" +
	"s apikey <command> [options]\x0a\x0aCommands:\x0a  generate    Generate " +
	"a new API key\x0a  list        List all API keys\x0a  revoke      Revoke" +
	" an API key\x0a  help        Show this help\x0a\x0aGenerate Options:\x0a" +
	"  --name <name>           Name for the key (required)\x0a  --permissions" +
	" <perms>   Comma-separated permissions (required)\x0a  --expires <durati" +
	"on>    Expiration (e.g., \x2224h\x22, \x227d\x22, \x2230d\x22)\x0a  --al" +
	"lowed-ips <ips>     Comma-separated allowed IPs\x0a  --rate-limit <rpm> " +
	"     Requests per minute limit\x0a  --description <desc>    Description" +
	"\x0a  --json, -j              Output in JSON format (for scripting)\x0a" +
	"\x0aPermission Values:\x0a  Read:   config:read, uplinks:read, firewall:" +
	"read, dhcp:read, dns:read,\x0a          learning:read, metrics:read, hea" +
	"lth:read, logs:read, read:*\x0a  Write:  config:write, uplinks:write, fi" +
	"rewall:write, dhcp:write,\x0a          dns:write, learning:write, write:" +
	"*\x0a  Admin:  admin:keys, admin:system, admin:backup, admin:*\x0a  All:" +
	"    * (full access)\x0a\x0aPreset Permissions:\x0a  --preset readonly   " +
	"    Read-only access to all resources\x0a  --preset uplink         Uplin" +
	"k management (read/write uplinks, read health)\x0a  --preset monitoring " +
	"    Metrics, health, and logs (read-only)\x0a  --preset admin          F" +
	"ull administrative access\x0a\x0aExamples:\x0a  # Generate a read-only k" +
	"ey\x0a  %[3]s apikey generate --name \x22monitoring\x22 --preset readonl" +
	"y\x0a\x0a  # Generate an uplink control key for your script\x0a  %[4]s a" +
	"pikey generate --name \x22vpn-switcher\x22 --preset uplink --expires 365" +
	"d\x0a\x0a  # Generate a full admin key\x0a  %[5]s apikey generate --name" +
	" \x22admin-key\x22 --preset admin\x0a\x0a  # Generate a key with specifi" +
	"c permissions\x0a  %[6]s apikey generate --name \x22custom\x22 --permiss" +
	"ions \x22uplinks:read,uplinks:write\x22\x0a\x0a  # Generate a key restri" +
	"cted to specific IPs\x0a  %[7]s apikey generate --name \x22local-only" +
	"\x22 --preset admin --allowed-ips \x22127.0.0.1,192.168.1.0/24\x22\x04" +
	"\x00\x01\x0a\x0f\x02API Key: %[1]s\x04\x02  \x01\x0a\x13\x02ID:         " +
	" %[1]s\x04\x02  \x01\x0a\x13\x02Name:        %[1]s\x04\x02  \x01\x0a\x13" +
	"\x02Prefix:      %[1]s\x04\x02  \x01\x0a\x13\x02Permissions: %[1]v\x04" +
	"\x02  \x01\x0a\x13\x02Expires:     %[1]s\x04\x02  \x01\x0a\x13\x02Allowe" +
	"d IPs: %[1]v\x04\x02  \x01\x0a\x1b\x02Rate Limit:  %[1]d req/min\x04\x02" +
	"  \x01\x0aD\x02curl -H \x22Authorization: Bearer %[1]s\x22 http://localh" +
	"ost:8080/api/...\x04\x02  \x01\x0a9\x02curl -H \x22X-API-Key: %[1]s\x22 " +
	"http://localhost:8080/api/...\x04\x00\x01\x0a\x13\x02Key %[1]s revoked." +
	"\x04\x00\x01\x0a\x0d\x02Error: %[1]v\x04\x00\x01\x0a\x15\x02Configuratio" +
	"n valid!\x04\x00\x01\x0a\x16\x02Schema Version: %[1]s\x04\x00\x01\x0a" +
	"\x12\x02Interfaces: %[1]d\x04\x00\x01\x0a\x0d\x02Zones: %[1]d\x04\x00" +
	"\x01\x0a\x10\x02Policies: %[1]d\x04\x00\x01\x0a\x1a\x02Migration: %[1]s " +
	"-> %[2]s\x04\x00\x01\x0a'\x02Error generating firewall rules: %[1]v\x04" +
	"\x00\x01\x0a+\x02Error initializing firewall manager: %[1]v\x04\x00\x02" +
	"\x0a\x0a\x1e\x02Unknown config command: %[1]s\x04\x00\x01\x0a*\x02Failed" +
	" to connect to control plane: %[1]v\x04\x00\x01\x0a+\x02Make sure 'firew" +
	"all ctl' is running first.\x04\x00\x01\x0a#\x02Failed to get configurati" +
	"on: %[1]v\x02%[1]s\x04\x00\x01\x0a\x1d\x02Invalid output format: %[1]s" +
	"\x04\x00\x01\x0a\x22\x02Failed to read config file: %[1]v\x04\x00\x01" +
	"\x0a!\x02Failed to read from stdin: %[1]v\x04\x00\x01\x0a'\x02Configurat" +
	"ion validation failed: %[1]v\x04\x00\x01\x0a(\x02Warning: Failed to crea" +
	"te backup: %[1]v\x04\x00\x01\x0a(\x02Warning: Failed to create backup: %" +
	"[1]s\x04\x00\x01\x0a\x1e\x02Backup created: version %[1]d\x04\x00\x01" +
	"\x0a#\x02Failed to set configuration: %[1]v\x04\x00\x01\x0a$\x02Error ap" +
	"plying configuration: %[1]s\x04\x00\x01\x0a4\x02You can restore from bac" +
	"kup version %[1]d if needed\x04\x00\x01\x0a\x19\x02Validation failed: %[" +
	"1]v\x04\x00\x01\x0a'\x02Failed to create temporary file: %[1]v\x04\x00" +
	"\x01\x0a&\x02Failed to write temporary file: %[1]v\x04\x00\x01\x0a\x15" +
	"\x02Editor failed: %[1]v\x04\x00\x01\x0a\x22\x02Failed to read edited fi" +
	"le: %[1]v\x04\x00\x01 )\x02Options: [r]etry, [a]bort, [e]dit again:\x04" +
	"\x00\x01\x0a%\x02Failed to apply configuration: %[1]v\x04\x00\x01\x0aB" +
	"\x02Usage: firewall config delete <section-type> [label1] [label2]..." +
	"\x04\x00\x01\x0a&\x02Examples: firewall config delete dhcp\x04\x0a      " +
	"    \x01\x0a&\x02firewall config delete interface eth0\x04\x0a          " +
	"\x01\x0a&\x02firewall config delete policy lan wan\x04\x0a          \x01" +
	"\x0a4\x02firewall config delete policy \x22allow ssh\x22 (by name)\x02De" +
	"lete %[1]s\x04\x01 \x00\x12\x02with labels %[1]v\x04\x00\x01 \x09\x02? [" +
	"y/N]:\x04\x00\x01\x0a \x02Failed to delete section: %[1]v\x04\x00\x01" +
	"\x0a\x1e\x02Error deleting section: %[1]s\x02Successfully deleted %[1]s" +
	"\x04\x00\x01\x0a\x22\x02Failed to load config file: %[1]v\x04\x00\x01" +
	"\x0a\x18\x02Migration failed: %[1]v\x04\x00\x01\x0a\x1f\x02Canonicalizat" +
	"ion failed: %[1]v\x04\x00\x01\x0a\x1e\x02Failed to generate HCL: %[1]v" +
	"\x04\x00\x01\x0a&\x02Failed to save migrated config: %[1]v\x04\x00\x01" +
	"\x0a4\x02Successfully migrated %[1]s to schema version %[2]s\x04\x00\x01" +
	"\x0a&\x02Failed to enable debug logging: %[1]v\x04\x00\x01\x0a\x1d\x02Er" +
	"ror running console: %[1]v\x04\x00\x01\x0a\x1b\x02Clock anchor loaded: %" +
	"[1]s\x04\x00\x01\x0ai\x02Warning: System time (%[1]s) appears unreasonab" +
	"le. Last known good time was %[2]s. Waiting for NTP sync.\x04\x00\x01" +
	"\x0aM\x02Warning: System time (%[1]s) appears unreasonable and no anchor" +
	" file exists.\x04\x00\x01\x0a \x02Error: unsupported type '%[1]s'\x04" +
	"\x00\x01\x0a(\x02Parsed backup file: %[1]s (Type: %[2]s)\x04\x00\x01\x0a" +
	"\x1c\x02Error parsing backup: %[1]v\x04\x00\x01\x0a=\x02Found: %[1]d int" +
	"erfaces, %[2]d filter rules, %[3]d NAT rules\x04\x00\x01\x0a\x1c\x02Erro" +
	"r writing config: %[1]v\x04\x00\x01\x0a\x1f\x02Configuration written to " +
	"%[1]s\x04\x00\x01\x0a\x08\x02- %[1]s\x04\x00\x02\x0a\x0a\x1d\x02Unknown " +
	"ipset command: %[1]s\x04\x00\x01\x0a.\x02Error: Failed to connect to API" +
	" server: %[1]v\x04\x00\x01\x0a(\x02Error: API server returned status %[1" +
	"]d\x04\x00\x01\x0a&\x02Error: Failed to read response: %[1]v\x04\x00\x01" +
	"\x0a'\x02Error: Failed to parse response: %[1]v\x04\x00\x02\x0a\x0a\x16" +
	"\x02IPSets (%[1]d total):\x04\x00\x01\x0a3\x02%-20[1]s %-12[2]s %-12[3]s" +
	" %-10[4]s %-15[5]s %[6]s\x04\x00\x01\x0a3\x02%-20[1]s %-12[2]s %-12[3]s " +
	"%-10[4]d %-15[5]s %[6]s\x04\x00\x01\x0a\x1e\x02Error: IPSet name is requ" +
	"ired\x04\x00\x01\x0a\x22\x02Usage: firewall ipset show <name>\x04\x00" +
	"\x01\x0a\x1f\x02Error: IPSet '%[1]s' not found\x04\x00\x02\x0a\x0a\x0f" +
	"\x02IPSet Details:\x04\x00\x01\x0a\x14\x02Name:         %[1]s\x04\x00" +
	"\x01\x0a\x14\x02Type:         %[1]s\x04\x00\x01\x0a\x14\x02Source:      " +
	" %[1]s\x04\x00\x01\x0a\x14\x02Source URL:   %[1]s\x04\x00\x01\x0a\x14" +
	"\x02Entries:      %[1]d\x04\x00\x01\x0a\x14\x02Last Update:  %[1]s\x04" +
	"\x00\x01\x0a\x14\x02Age:          %[1]s\x04\x00\x01\x0a\x14\x02Next Upda" +
	"te:  %[1]s\x04\x00\x01\x0a$\x02Usage: firewall ipset update <name>\x04" +
	"\x00\x01\x0a%\x02Usage: firewall ipset refresh <name>\x04\x00\x01\x0a!" +
	"\x02Error: Cache command is required\x04\x00\x01\x0a)\x02Usage: firewall" +
	" ipset cache <info|clear>\x04\x00\x01\x0a\x1d\x02Unknown cache command: " +
	"%[1]s\x04\x00\x02\x0a\x0a\x19\x02IPSet Cache Information:\x04\x00\x01" +
	"\x0a\x14\x02Cached Lists: %[1]d\x04\x00\x01\x0a\x1a\x02Total Size:   %[1" +
	"]d bytes\x04\x00\x01\x0a\x14\x02Cache Dir:    %[1]s\x04\x00\x01\x0a'\x02" +
	"Error: Failed to create request: %[1]v\x04\x00\x01\x0a\x13\x02Connected " +
	"to %[1]s\x04\x00\x01\x0a&\x02Server Certificate Fingerprint: %[1]s\x04" +
	"\x00\x01\x0a1\x02To pin this certificate, use --fingerprint %[1]s\x04" +
	"\x00\x01\x0a\x1a\x02Error polling logs: %[1]v\x04\x00\x01\x0a\x1b\x02%[1" +
	"]s [%[2]s] %[3]s: %[4]s\x04\x00\x01\x0a+\x02Failed to determine executab" +
	"le path: %[1]v\x04\x00\x01\x0a&\x02Monitor: Failed to start child: %[1]v" +
	"\x04\x00\x01\x0a(\x02Monitor: Started glacic ctl (pid=%[1]d)\x04\x00\x01" +
	"\x0a-\x02Monitor: Forwarding signal %[1]v to child...\x04\x00\x01\x0aH" +
	"\x02Monitor: Child crashed with exit code %[1]d (err: %[2]v). Restarting" +
	"...\x04\x00\x01\x0aJ\x02Monitor: Detected crash loop (%[1]d fast crashes" +
	"). Backing off for 30s...\x04\x00\x01\x0a \x02Validating configuration: " +
	"%[1]s\x04\x00\x01\x0a#\x02Sending SIGHUP to process %[1]d...\x04\x00\x01" +
	"\x0a\x1e\x02Error: setup must run as root\x04\x00\x01\x0a\x14\x02Setup f" +
	"ailed: %[1]v\x04\x00\x01\x0a*\x02Warning: failed to initialize auth: %[1" +
	"]v\x04\x00\x01\x0a,\x02Warning: failed to create admin user: %[1]v\x04" +
	"\x02  \x01\x0a$\x021. Start the firewall:  %[1]s start\x04\x02  \x01\x0a" +
	"'\x022. Access the UI:       https://%[1]s/\x04\x00\x01\x0a\x1e\x02Error" +
	": reset must run as root\x04\x00\x01\x0a \x02Error reading config dir: %" +
	"[1]v\x04\x00\x01\x0a'\x02Warning: failed to remove %[1]s: %[2]v\x04\x00" +
	"\x01\x0a'\x02Warning: Removing stale PID file %[1]s\x04\x00\x01\x0a\x1b" +
	"\x02Started %[1]s (PID: %[2]d)\x04\x00\x01\x0a\x0c\x02Logs: %[1]s\x04" +
	"\x01\x0a\x01\x0a\x22\x02Error: Daemon exited immediately.\x04\x00\x01" +
	"\x0a\x0c\x02Log output:\x04\x02  \x01\x0a\x06\x02%[1]s\x04\x00\x01\x0a7" +
	"\x02Is the daemon running? Start with: glacic ctl <config>\x04\x00\x01" +
	"\x0a\x1c\x02Failed to get status: %[1]v\x04\x00\x01\x0a\x0f\x02Uptime:  " +
	"%[1]s\x04\x00\x01\x0a\x0f\x02Config:  %[1]s\x04\x00\x01\x0a'\x02Warning:" +
	" Failed to get services: %[1]v\x04\x02  \x01\x0a\x0f\x02%-12[1]s %[2]s" +
	"\x04\x00\x01\x0a)\x02Warning: Failed to get interfaces: %[1]v\x04\x02  " +
	"\x01\x0a\x1f\x02%-10[1]s %-6[2]s %-8[3]s %[4]s\x04\x00\x01\x0a\x1f\x02St" +
	"opping %[1]s (PID: %[2]d)...\x02Method not allowed\x02Version is require" +
	"d\x02Version parameter required\x02Invalid version\x02max_backups must b" +
	"e at least 1\x02Control plane not connected\x02Invalid request body\x02T" +
	"ask ID required\x02Control plane client not connected\x02Failed to clone" +
	" config\x02Failed to read request body\x02Invalid DNS configuration form" +
	"at\x02Device ID is required\x02MAC and IdentityID are required\x02MAC is" +
	" required\x02Section type required (use ?type=dhcp)\x02Interface name re" +
	"quired\x02name parameter required\x02Configuration not loaded\x02CIDR is" +
	" required\x02IP address is required\x02Control Plane Disconnected\x02Too" +
	" many requests in batch\x02Rate limit exceeded for batch\x02Certificate " +
	"not found\x02Collector not initialized\x02policy_name and relative_to ar" +
	"e required\x02Policy not found\x02policy_name is required\x02rule_name a" +
	"nd relative_to are required\x02Rule not found\x02Page not found\x02Too m" +
	"any login attempts. Please try again later.\x02Auth not configured\x02In" +
	"valid credentials\x02Too many setup attempts. Please try again later." +
	"\x02Admin already exists\x02Username and password required\x02Failed to " +
	"initialize auth\x02Username required\x02User not found\x02Cannot delete " +
	"admin user\x02Missing 'checksum' field\x02Missing 'arch' field\x02MAC ad" +
	"dress is required\x04\x00\x01\x0a/\x02Error: --binary is required for re" +
	"mote upgrade\x04\x00\x01\x0a0\x02Error: --api-key is required for remote" +
	" upgrade\x04\x00\x01\x0a$\x02%[1]s\x09%[2]d\x09%[3]s\x09%[4]s\x09%[5]s" +
	"\x09%[6]s\x04\x00\x01\x0a\x0c\x02%[1]s\x09%[2]s\x04\x00\x01\x0a\x12\x02%" +
	"[1]s\x09%[2]s\x09%[3]d\x04\x00\x01 !\x02Apply this configuration? [y/N]:" +
	"\x04\x00\x01\x0a3\x02Error: --api-key is required for remote connection" +
	"\x04\x00\x01\x0a\x1b\x02Error: --input is required"

	// Total table size 25232 bytes (24KiB); checksum: 8943B338
